### ISSUE TITLE
Default dark theme hides line numbers

### ISSUE THREAD

**Issue by bobrocke** [osxpeppermint/peppermint#90]
The line numbers are too dark to read in the default dark theme:

![dark](https://cloud.githubusercontent.com/assets/2962426/8411109/2ee544ac-1e50-11e5-9e9e-a659fab7148b.jpeg)

**Comment by osxpeppermint** [comment]
Well, I have thought of changing it like 100 times, but always forget about it. Good point! ;-)

**Comment by osxpeppermint** [comment]
Fixed as of 1.5 beta 21. (I've also made a few minor changes - the most obvious of which is the info/warning/error markers - but there are lots pending. Let's see... :-) )

**Comment by bobrocke** [comment]
I'm running build 5065 and it's better, but still not very readable:

![open-a-terminal js peppermint](https://cloud.githubusercontent.com/assets/2962426/8481877/d85f4ae0-20b3-11e5-9900-606fa7529998.jpg)

**Comment by osxpeppermint** [comment]
Hmm... I tried to increase the contrast - but I guess it could have been increased more. Let me see...

P.S. What do you think of the other minor changes? (highlights/selection/bookmarks/info-warning-error markers)

**Comment by bobrocke** [comment]
I think the other color changes are fine; so much of a theme's colors are personal preference anyway. That's why there are so many custom themes for all the programmers' editors!

**Comment by osxpeppermint** [comment]
Well, obviously. I'm just focusing on this thing you mentioned with the gutter numbering, since it's one of those that bothered me as well. +seeing what other people like or not, given that's it the "default" theme, is not bad at all.
